feat: implement config-manager and gpio-manager
ThatDraenGuy/motorland pull request #16
Opened 2023-05-13 12:34 UTC by algoritmist

2023-05-13 13:47 UTC, Moleus requested changes
LGTM, but one files contains unresolved merge conflict

2023-05-13 13:47 UTC, Moleus commented on config_manager/temp/temp_parser.py
> +<<<<<<< HEAD
Please, remove these lines ;)

2023-05-13 19:23 UTC, algoritmist commented on config_manager/temp/temp_parser.py
> +<<<<<<< HEAD
done

2023-05-14 15:31 UTC, Moleus approved these changes

2023-05-14 15:31 UTC, merged