Feat/basic daemon impl
ThatDraenGuy/motorland pull request #17
Opened 2023-05-20 17:34 UTC by filberol

2023-05-21 11:34 UTC, Moleus requested changes
Please, make the following changes

2023-05-21 11:34 UTC, Moleus commented on motorsd/CMakeLists.txt
> +set(SOURCES src/daemon.c src/command_parser.c src/motor_invoker.c include/motor_invoker.h)
We don't need to use `GLOB_RECURSE SOURCES` if we manually specify source files here

2023-05-21 11:34 UTC, Moleus commented on motorsd/include/daemon.h
> +#ifndef MOTORLAND_DAEMON_H
In our project we use `#pragma once`

2023-05-21 11:34 UTC, Moleus commented on motorsd/include/daemon_utils.h
> +MotorCommand parseMotorCommand(const uint8_t* byteOrder, size_t size);
if this method is public API it should be prefixed with module name, such as `motorsd_parse_motor_command`

2023-05-21 11:34 UTC, Moleus commented on motorsd/include/daemon_utils.h
> +MotorCommand parseMotorCommand(const uint8_t* byteOrder, size_t size);
Also, follow snake_case convention

2023-05-21 11:34 UTC, Moleus commented on motorsd/src/command_parser.c
> +MotorCommand parseMotorCommand(const uint8_t* byteOrder, size_t size) {
What does `byteOrder` mean?

2023-05-21 11:34 UTC, Moleus commented on motorsd/src/command_parser.c
> +MotorCommand parseMotorCommand(const uint8_t* byteOrder, size_t size) {
use snake_case for all but Structures

2023-05-21 11:34 UTC, Moleus commented on motorsd/src/daemon.c
> +
In the following updates we will call `process_motor_command(command)` from here, am I right?

2023-05-21 11:34 UTC, Moleus commented on motorsd/test/test.c
> +int main(int argc, char *argv[]) {
Can u highlight somehow that this test represents a client connection to the server?

2023-05-28 19:07 UTC, Moleus submitted a review, later dismissed

2023-06-14 08:10 UTC, Moleus commented
Can we merge this one?

2023-06-16 09:07 UTC, ThatDraenGuy approved these changes
LGTM

2023-06-16 09:07 UTC, merged